server.port: ${service_port:3002}
spring:
  application.name: recommend

ottrecommend:
  filepath: ${ottrecommend_filepath:data/bestott.properties}
  authtoken: ${ottrecommend_authtoken:P@ssword!}

logging.level:
  root: INFO
  org.springframework.web: ERROR  